version: '2'

services:

  influxdb:
    image: influxdb
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - '8086:8086'

  grafana:
    image: grafana/grafana
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - '3000:3000'
    links:
      - influxdb
    depends_on:
      - influxdb
